#!/bin/bash

# 첫 번째 인자를 RPC 주소로, 두 번째 인자를 프라이빗키로 사용
if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Usage: $0 <rpc-url> <private-key>"
  exit 1
fi
RPC_URL="$1"
PRIVATE_KEY="$2"
CREATEX_DEPLOYER="0xeD456e05CaAb11d66C4c797dD6c1D6f9A7F352b5"
CREATEX_ADDR="0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed"

# 잔액 조회 (wei 단위)
deployer_balance=$(cast balance "$CREATEX_DEPLOYER" -r "$RPC_URL")

# 잔액이 0이면 이더 전송
if [ "$deployer_balance" = 0 ]; then
  echo "Sending ETH to $CREATEX_DEPLOYER ..."
  cast send "$CREATEX_DEPLOYER" \
    --value 300000000000000000 \
    -r "$RPC_URL" \
    --private-key "$PRIVATE_KEY"
else
  echo "Balance is not zero ($deployer_balance wei), skipping funding."
fi

code=$(cast code "$CREATEX_ADDR" -r "$RPC_URL")

if [ "$code" = 0x ]; then
  echo "Deploy CreateX at $CREATEX_ADDR ..."
  # presigned tx json 다운받기 및 쌍따옴표 제거
  json=$(curl -s https://raw.githubusercontent.com/pcaversaccio/createx/refs/heads/main/scripts/presigned-createx-deployment-transactions/signed_serialised_transaction_gaslimit_3000000_.json | tr -d '"')

  # 트랜잭션 publish
  cast publish $json -r "$RPC_URL" 2>&1
else
  echo "CreateX allready deployed ac "$CREATEX_ADDR". skipping deploy."
fi

